# patterns.py
import re

# Lista wzorców (skopiowana i sformatowana pod Python)
RAW_PATTERNS = [
    {"id": "gitlab-pat", "pattern": r"glpat-[0-9a-zA-Z\-\_]{20}"},
    {"id": "aws-access-token", "pattern": r"(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"},
    {"id": "azure-api-key", "pattern": r"AccountKey=[a-zA-Z0-9+\/=]{60,100}"},
    {"id": "gcp-api-key", "pattern": r"AIza[0-9A-Za-z_\-]{30,40}"},
    {"id": "jwt", "pattern": r"eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}"},
    {"id": "aws-secret-key", "pattern": r"(aws[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}[0-9a-zA-Z\/+]{40}", "flags": re.IGNORECASE},
    {"id": "aws-mws-key", "pattern": r"amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"},
    {"id": "PKCS8-PK", "pattern": r"-----BEGIN PRIVATE KEY-----"},
    {"id": "RSA-PK", "pattern": r"-----BEGIN RSA PRIVATE KEY-----"},
    {"id": "OPENSSH-PK", "pattern": r"-----BEGIN OPENSSH PRIVATE KEY-----"},
    {"id": "PGP-PK", "pattern": r"-----BEGIN PGP PRIVATE KEY BLOCK-----"},
    {"id": "github-pat", "pattern": r"ghp_[0-9a-zA-Z]{36}"},
    {"id": "github-oauth", "pattern": r"gho_[0-9a-zA-Z]{36}"},
    {"id": "SSH-DSA-PK", "pattern": r"-----BEGIN DSA PRIVATE KEY-----"},
    {"id": "SSH-EC-PK", "pattern": r"-----BEGIN EC PRIVATE KEY-----"},
    {"id": "github-app-token", "pattern": r"(ghu|ghs)_[0-9a-zA-Z]{36}"},
    {"id": "github-refresh-token", "pattern": r"ghr_[0-9a-zA-Z]{76}"},
    {"id": "shopify-shared-secret", "pattern": r"shpss_[a-fA-F0-9]{32}"},
    {"id": "shopify-access-token", "pattern": r"shpat_[a-fA-F0-9]{32}"},
    {"id": "shopify-custom-access-token", "pattern": r"shpca_[a-fA-F0-9]{32}"},
    {"id": "shopify-private-app-access-token", "pattern": r"shppa_[a-fA-F0-9]{32}"},
    {"id": "slack-access-token", "pattern": r"xox[baprs]-([0-9a-zA-Z]{10,48})?"},
    {"id": "stripe-access-token", "pattern": r"(sk|pk)_(test|live)_[0-9a-z]{10,32}", "flags": re.IGNORECASE},
    {"id": "pypi-upload-token", "pattern": r"pypi-AgEIcHlwaS5vcmc[A-Za-z0-9\-_]{50,1000}"},
    {"id": "gcp-service-account", "pattern": r'"type": "service_account"'},
    {"id": "heroku-api-key", "pattern": r"""(heroku[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})['"]""", "flags": re.IGNORECASE},
    {"id": "slack-web-hook", "pattern": r"https:\/\/hooks.slack.com\/services\/T[a-zA-Z0-9_]{8}\/B[a-zA-Z0-9_]{8,12}\/[a-zA-Z0-9_]{24}"},
    {"id": "twilio-api-key", "pattern": r"SK[0-9a-fA-F]{32}"},
    {"id": "age-secret-key", "pattern": r"AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}"},
    {"id": "facebook-token", "pattern": r"""(facebook[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "twitter-token", "pattern": r"""(twitter[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{35,44})['"]""", "flags": re.IGNORECASE},
    {"id": "adobe-client-id", "pattern": r"""(adobe[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "adobe-client-secret", "pattern": r"(p8e-)[a-z0-9]{32}", "flags": re.IGNORECASE},
    {"id": "alibaba-access-key-id", "pattern": r"(LTAI)[a-z0-9]{20}", "flags": re.IGNORECASE},
    {"id": "alibaba-secret-key", "pattern": r"""(alibaba[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]""", "flags": re.IGNORECASE},
    {"id": "asana-client-id", "pattern": r"""(asana[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{16})['"]""", "flags": re.IGNORECASE},
    {"id": "asana-client-secret", "pattern": r"""(asana[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "atlassian-api-token", "pattern": r"""(atlassian[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{24})['"]""", "flags": re.IGNORECASE},
    {"id": "bitbucket-client-id", "pattern": r"""(bitbucket[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "bitbucket-client-secret", "pattern": r"""(bitbucket[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9_\-]{64})['"]""", "flags": re.IGNORECASE},
    {"id": "beamer-api-token", "pattern": r"""(beamer[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"](b_[a-z0-9=_\-]{44})['"]""", "flags": re.IGNORECASE},
    {"id": "clojars-api-token", "pattern": r"(CLOJARS_)[a-z0-9]{60}", "flags": re.IGNORECASE},
    {"id": "contentful-delivery-api-token", "pattern": r"""(contentful[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9\-=_]{43})['"]""", "flags": re.IGNORECASE},
    {"id": "databricks-api-token", "pattern": r"dapi[a-h0-9]{32}"},
    {"id": "discord-api-token", "pattern": r"""(discord[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{64})['"]""", "flags": re.IGNORECASE},
    {"id": "discord-client-id", "pattern": r"""(discord[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{18})['"]""", "flags": re.IGNORECASE},
    {"id": "discord-client-secret", "pattern": r"""(discord[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_\-]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "doppler-api-token", "pattern": r"['\"](dp\.pt\.)[a-z0-9]{43}['\"]", "flags": re.IGNORECASE},
    {"id": "dropbox-api-secret", "pattern": r"""(dropbox[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{15})['"]""", "flags": re.IGNORECASE},
    {"id": "dropbox-short-lived-api-token", "pattern": r"""(dropbox[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"](sl\.[a-z0-9\-=_]{135})['"]""", "flags": re.IGNORECASE},
    {"id": "dropbox-long-lived-api-token", "pattern": r"""(dropbox[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"][a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\-_=]{43}['"]""", "flags": re.IGNORECASE},
    {"id": "duffel-api-token", "pattern": r"['\"]duffel_(test|live)_[a-z0-9_-]{43}['\"]", "flags": re.IGNORECASE},
    {"id": "dynatrace-api-token", "pattern": r"['\"]dt0c01\.[a-z0-9]{24}\.[a-z0-9]{64}['\"]", "flags": re.IGNORECASE},
    {"id": "easypost-api-token", "pattern": r"['\"]EZAK[a-z0-9]{54}['\"]", "flags": re.IGNORECASE},
    {"id": "easypost-test-api-token", "pattern": r"['\"]EZTK[a-z0-9]{54}['\"]", "flags": re.IGNORECASE},
    {"id": "fastly-api-token", "pattern": r"""(fastly[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9\-=_]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "finicity-client-secret", "pattern": r"""(finicity[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{20})['"]""", "flags": re.IGNORECASE},
    {"id": "finicity-api-token", "pattern": r"""(finicity[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "flutterwave-public-key", "pattern": r"FLWPUBK_TEST-[a-h0-9]{32}-X", "flags": re.IGNORECASE},
    {"id": "flutterwave-secret-key", "pattern": r"FLWSECK_TEST-[a-h0-9]{32}-X", "flags": re.IGNORECASE},
    {"id": "flutterwave-enc-key", "pattern": r"FLWSECK_TEST[a-h0-9]{12}"},
    {"id": "frameio-api-token", "pattern": r"fio-u-[a-z0-9\-_=]{64}", "flags": re.IGNORECASE},
    {"id": "gocardless-api-token", "pattern": r"['\"]live_[a-z0-9\-_=]{40}['\"]", "flags": re.IGNORECASE},
    {"id": "grafana-api-token", "pattern": r"['\"]eyJrIjoi[a-z0-9\-_=]{72,92}['\"]", "flags": re.IGNORECASE},
    {"id": "hashicorp-tf-api-token", "pattern": r"['\"][a-z0-9]{14}\.atlasv1\.[a-z0-9\-_=]{60,70}['\"]", "flags": re.IGNORECASE},
    {"id": "hubspot-api-token", "pattern": r"""(hubspot[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]""", "flags": re.IGNORECASE},
    {"id": "intercom-api-token", "pattern": r"""(intercom[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_]{60})['"]""", "flags": re.IGNORECASE},
    {"id": "intercom-client-secret", "pattern": r"""(intercom[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]""", "flags": re.IGNORECASE},
    {"id": "ionic-api-token", "pattern": r"""(ionic[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"](ion_[a-z0-9]{42})['"]""", "flags": re.IGNORECASE},
    {"id": "ionic-api-token-standalone", "pattern": r"\bion_[a-z0-9]{42}\b", "flags": re.IGNORECASE},
    {"id": "linear-api-token", "pattern": r"lin_api_[a-z0-9]{40}", "flags": re.IGNORECASE},
    {"id": "linear-client-secret", "pattern": r"""(linear[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "lob-api-key", "pattern": r"""(lob[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((live|test)_[a-f0-9]{35})['"]""", "flags": re.IGNORECASE},
    {"id": "lob-pub-api-key", "pattern": r"""(lob[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((test|live)_pub_[a-f0-9]{31})['"]""", "flags": re.IGNORECASE},
    {"id": "lob-api-key-standalone", "pattern": r"((live|test)_[a-f0-9]{35})", "flags": re.IGNORECASE},
    {"id": "lob-pub-api-key-standalone", "pattern": r"((test|live)_pub_[a-f0-9]{31})", "flags": re.IGNORECASE},
    {"id": "mailchimp-api-key", "pattern": r"""(mailchimp[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32}-us20)['"]""", "flags": re.IGNORECASE},
    {"id": "mailgun-private-api-token", "pattern": r"""(mailgun[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"](key-[a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "mailgun-pub-key", "pattern": r"""(mailgun[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"](pubkey-[a-f0-9]{32})['"]""", "flags": re.IGNORECASE},
    {"id": "mailgun-signing-key", "pattern": r"""(mailgun[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})['"]""", "flags": re.IGNORECASE},
    {"id": "mapbox-api-token", "pattern": r"(pk\.[a-z0-9]{60}\.[a-z0-9]{22})", "flags": re.IGNORECASE},
    {"id": "messagebird-api-token", "pattern": r"""(messagebird[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{25})['"]""", "flags": re.IGNORECASE},
    {"id": "messagebird-client-id", "pattern": r"""(messagebird[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]""", "flags": re.IGNORECASE},
    {"id": "new-relic-user-api-key", "pattern": r"['\"](NRAK-[A-Z0-9]{27})['\"]"},
    {"id": "new-relic-user-api-id", "pattern": r"""(newrelic[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([A-Z0-9]{64})['"]""", "flags": re.IGNORECASE},
    {"id": "new-relic-browser-api-token", "pattern": r"['\"](NRJS-[a-f0-9]{19})['\"]"},
    {"id": "npm-access-token", "pattern": r"['\"](npm_[a-z0-9]{36})['\"]", "flags": re.IGNORECASE},
    {"id": "planetscale-password", "pattern": r"pscale_pw_[a-z0-9\-_\.]{43}", "flags": re.IGNORECASE},
    {"id": "planetscale-api-token", "pattern": r"pscale_tkn_[a-z0-9\-_\.]{43}", "flags": re.IGNORECASE},
    {"id": "postman-api-token", "pattern": r"PMAK-[a-f0-9]{24}\-[a-f0-9]{34}", "flags": re.IGNORECASE},
    {"id": "pulumi-api-token", "pattern": r"pul-[a-f0-9]{40}"},
    {"id": "rubygems-api-token", "pattern": r"rubygems_[a-f0-9]{48}"},
    {"id": "sendgrid-api-token", "pattern": r"SG\.[a-z0-9_\-\.]{66}", "flags": re.IGNORECASE},
    {"id": "sendinblue-api-token", "pattern": r"xkeysib-[a-f0-9]{64}\-[a-z0-9]{16}", "flags": re.IGNORECASE},
    {"id": "shippo-api-token", "pattern": r"shippo_(live|test)_[a-f0-9]{40}"},
    {"id": "linkedin-client-secret", "pattern": r"""(linkedin[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z]{16})['"]""", "flags": re.IGNORECASE},
    {"id": "linkedin-client-id", "pattern": r"""(linkedin[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{14})['"]""", "flags": re.IGNORECASE},
    {"id": "twitch-api-token", "pattern": r"""(twitch[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]""", "flags": re.IGNORECASE},
    {"id": "typeform-api-token", "pattern": r"""(typeform[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}(tfp_[a-z0-9\-_\.=]{59})""", "flags": re.IGNORECASE},
    {"id": "database-connection-uri", "pattern": r"(redis|postgres|postgresql|mysql|mongodb|amqp):\/\/[^:]*:([^@]+)@"},
    {"id": "generic-api-key", "pattern": r"""((key|api[^Version]|token|secret|password)[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9a-zA-Z\-_=!.?@#$%^&*]{8,64})['"]""", "flags": re.IGNORECASE},
    {"id": "email", "pattern": r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}", "flags": re.IGNORECASE},
    {"id": "ip-address", "pattern": r"((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)"},
]